openapi: 3.0.0
info:
  title: Subscriptions
  version: '1.0'
servers:
  - url: 'https://invoiceapi-dev.horizonafs.io'
paths:
  '/subscriptions/customers/{id}':
    post:
      summary: Create New User
      operationId: post-subscription
      responses:
        '200':
          description: Subscription posted
          content:
            application/json:
              schema:
                $ref: ../models/subscriptions.v1.yaml
              examples:
                New User Bob Fellow:
                  value:
                    id: 12
                    firstName: Bob
                    lastName: Fellow
                    email: bob.fellow@gmail.com
                    dateOfBirth: '1996-08-24'
                    emailVerified: false
                    createDate: '2020-11-18'
        '400':
          description: Missing Required Information
        '409':
          description: Email Already Taken
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/PostCustomerSubscription.v1.yaml
            examples:
              Create User Bob Fellow:
                value:
                  firstName: Bob
                  lastName: Fellow
                  email: bob.fellow@gmail.com
                  dateOfBirth: '1996-08-24'
        description: Post the necessary fields for the API to create a new user.
      description: Post a new subscription
    get:
      summary: ''
      operationId: ''
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/CustomerSubscriptionResponse.v1.yaml
      description: Get customer subscriptions
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
  /subscriptions/types:
    get:
      summary: Get all subscription types
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties: {}
      operationId: get-subscriptions-types
    post:
      summary: Post a subscription type
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ''
      operationId: post-subscriptions-types
      requestBody:
        content:
          application/json:
            schema:
              $ref: ''
    put:
      summary: Edit a subscription type
      tags: []
      responses: {}
      operationId: put-subscriptions-types
  '/subscriptions/addendum/{id}':
    post:
      summary: Post a subscription addendum
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Addendumresponse.v1.yaml
      operationId: post-subscriptions-addendum
      description: 'Use this to post a addendum for one or several terms in a subscription. This can for example be a discount, startup fee, or hardware purchased in connection with the subscription.'
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/SubscriptionAddendum.v1.yaml
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: ''
      operationId: get-subscriptions-addendum-id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Addendumresponse.v1.yaml
      description: Get addendum details
  '/subscriptions/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: Get a subscription
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/subscriptions.v1.yaml
      operationId: get-subscriptions-id
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      x-examples:
        Alice Smith:
          id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
        createDate:
          type: string
          format: date
          description: The date that the user was created.
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
